allow_entities_without_labels: true
index: false
testmode: false
batch: true
safe_label: loose
batch_size: 100000000
relation_type_threshold: 0.95
represent_values_and_annotations_as_json:
  iris:
    - "http://purl.obolibrary.org/obo/IAO_0000115"
    - "http://www.geneontology.org/formats/oboInOwl#hasExactSynonym"
    - "http://www.geneontology.org/formats/oboInOwl#hasNarrowSynonym"
    - "http://www.geneontology.org/formats/oboInOwl#hasBroadSynonym"
    - "http://www.geneontology.org/formats/oboInOwl#hasRelatedSynonym"

neo_node_labelling:
  - classes:
      - CL:0000129
      - RO:0015002 some CL:0000129
    label: Microglia
  - classes:
      - CL:4023072
      - RO:0015002 some CL:4023072
    label: Vascular
  - classes:
      - CL:0000057
      - RO:0015002 some CL:0000057
    label: Fibroblast
  - classes:
      - CL:0002453
      - RO:0015002 some CL:0002453
    label: Oligodendrocyte precursor
  - classes:
      - CL:4023059
      - RO:0015002 some CL:4023059
    label: Committed oligodendrocyte precursor
  - classes:
      - CL:0000128
      - RO:0015002 some CL:0000128
    label: Oligodendrocyte
  - classes:
      - CL:0000127
      - RO:0015002 some CL:0000127
    label: Astrocyte
  - classes:
      - CL:0000065
      - RO:0015002 some CL:0000065
    label: Ependymal
  - classes:
      - CL:4023073
      - RO:0015002 some CL:4023073
    label: Choroid plexus
  - classes:
      - CL:4023012
      - RO:0015002 some CL:4023012
    label: DL NP
  - classes:
      - CL:0000679
      - RO:0015002 some CL:0000679
    label: DL corticothalamic
  - classes:
      - CL:4023060
      - RO:0015002 some CL:4023060
    label: Hippocampal CA1_3
  - classes:
      - CL:4023008
      - RO:0015002 some CL:4023008
    label: UL intratelencephalic
  - classes:
      - CL:4023008
      - RO:0015002 some CL:4023008
    label: DL intratelencephalic
  - classes:
      - CL:4023039
      - RO:0015002 some CL:4023039
    label: Amygdala excitatory    
  - classes:
      - CL:4023061
      - RO:0015002 some CL:4023061
    label: Hippocampal CA4 
  - classes:
      - CL:4023062
      - RO:0015002 some CL:4023062
    label: Hippocampal DG 
  - classes:
      - CL:1001474
      - RO:0015002 some CL:1001474
    label: Medium spiny neuron 
  - classes:
      - CL:1001474
      - RO:0015002 some CL:1001474
    label: Eccentric MSN 
  - classes:
      - CL:4023063
      - RO:0015002 some CL:4023063
    label: MGE 
  - classes:
      - CL:0000402
      - RO:0015002 some CL:0000402
    label: LAMP5_LHX6 
  - classes:
      - CL:4023064
      - RO:0015002 some CL:4023064
    label: CGE 
  - classes:
      - CL:4023057
      - RO:0015002 some CL:4023057
    label: Cerebellar 
  - classes:
      - CL:4023074
      - RO:0015002 some CL:4023074
    label: Mammillary body 
  - classes:
      - CL:4023068
      - RO:0015002 some CL:4023068
    label: MThalamic excitatory 
  - classes:
      - CL:4023079
      - RO:0015002 some CL:4023079
    label: MD inhibitory 



  - classes:
      - UBERON:0002616
      - RO:0015002 some UBERON:0002616
    label: Brain_Region
  - classes:
      - SO:0000704
      - RO:0015002 some SO:0000704
    label: Gene
  - classes:
      - PCL:0010001
      - RO:0015002 some PCL:0010001
    label: Cluster

    ## Brain regions
  - classes:
      - RO_0002100 some HBA:4327
    label: Amygdala
  - classes:
      - RO_0002100 some HBA:9131
    label: Pons
  - classes:
      - RO_0002100 some HBA:4249
    label: Hippocampus
  - classes:
      - RO_0002100 some HBA:9525
    label: Spinal cord
  - classes:
      - RO_0002100 some HBA:4300
    label: Basal forebrain
  - classes:
      - RO_0002100 some HBA:4540
    label: Hypothalamus
  - classes:
      - RO_0002100 some HBA:4008
    label: Cerebral cortex
  - classes:
      - RO_0002100 some HBA:9512
    label: Medulla
  - classes:
      - RO_0002100 some HBA:4696
    label: Cerebellum
  - classes:
      - RO_0002100 some HBA:9001
    label: Midbrain
  - classes:
      - RO_0002100 some HBA:4392
    label: Thalamus


curie_map:
  GITHUB: https://github.com/
  GITHUBH: http://github.com/
  PMID: http://www.ncbi.nlm.nih.gov/pubmed/
  orcid: https://orcid.org/
  doi: https://doi.org/
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  ncbigene: http://www.ncbi.nlm.nih.gov/gene/
  cc: http://creativecommons.org/ns#
  pato_rel: http://purl.obolibrary.org/obo/pato#
  so_rel: http://purl.obolibrary.org/obo/so#
  ro_rel: http://www.obofoundry.org/ro/ro.owl#
  owl: http://www.w3.org/2002/07/owl#
  skos: http://www.w3.org/2004/02/skos/core#
  ensembl: http://identifiers.org/ensembl/
  RO: http://purl.obolibrary.org/obo/RO_
  UBERON: http://purl.obolibrary.org/obo/UBERON_
  CL: http://purl.obolibrary.org/obo/CL_
  n2o: http://n2o.neo/custom/
  ILX: http://uri.interlex.org/base/ilx_
  NCBITaxon: http://purl.obolibrary.org/obo/NCBITaxon_
  PR: http://purl.obolibrary.org/obo/PR_
  SO: http://purl.obolibrary.org/obo/SO_
  OBI: http://purl.obolibrary.org/obo/OBI_
  PCL: http://purl.obolibrary.org/obo/PCL_

filters:
  solr:
    exclusion:
      iri_prefix:
        - http://virtualflybrain.org/reports/VFBc_
      neo4j_node_label:
        - Channel
